project:
  type: website
  output-dir: docs

website:
  title: "Геоинформатика и геоинформационные системы"
  page-footer: |
        © 2025, Татьяна Балтыжакова, Институт дизайна и урбанистики, Университет ИТМО
  navbar:
    left:
      - sidebar:practice
      - href: index.qmd
        text: Теория
      
      
    right: 
      - href: https://t.me/geomess
        icon: telegram
      - icon: github
        href: https://github.com/baltti/gis-dpo  
      
  sidebar:
    - id: practice
      title: "Практикум"
      style: "docked"
      collapse-level: 1
      contents:
        - start.qmd
        - basics.qmd
        - osm.qmd
        - georeferencing.qmd
        - style.qmd
        - crs.qmd
        - spatial.qmd
        - relief.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
lang: ru-RU    
language: custom.yml

editor: visual

